@startuml

title __JDBC-CRUD3's Class Diagram__\n

  package com.epam.training {
    package com.epam.training.application {
      class DemoApplication {
      }
    }
  }
  

  package com.epam.training {
    package com.epam.training.order {
      class Order {
      }
    }
  }
  

  package com.epam.training {
    package com.epam.training.revision {
      class Revision {
      }
    }
  }
  

  package com.epam.training {
    package com.epam.training.stock {
      class Stock {
      }
    }
  }
  

  package com.epam.training {
    package com.epam.training.stock {
      package com.epam.training.stock.repository {
        class StockRepository {
        }
      }
    }
  }
  

  package com.epam.training {
    package com.epam.training.stock {
      package com.epam.training.stock.controller {
        class StockRestController {
        }
      }
    }
  }
  

  package com.epam.training {
    package com.epam.training.stock {
      package com.epam.training.stock.service {
        class StockSchedulingServise {
        }
      }
    }
  }
  

  package com.epam.training {
    package com.epam.training.stock {
      package com.epam.training.stock.service {
        class StockService {
        }
      }
    }
  }
  

  DemoApplication -up-|> CommandLineRunner
  StockRepository -up-|> NamedParameterJdbcDaoSupport
  StockRestController o-- StockRepository : stockRepository
  StockRestController o-- StockService : stockService
  StockService o-- StockRepository : stockRepository


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
