spring:
  profiles.active: dev

---

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse_db?useSSL=false
    username: root

    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  sql:
    init:
      platform: mysql
  config:
    activate:
      on-profile: dev
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse_db?useSSL=false
    username: root
    password: '@Yyear7510'
    driver-class-name: com.mysql.jdbc.Driver
  sql:
    init:
      platform: mysql
  config:
    activate:
      on-profile:
server:
  tomcat:
    threads:
      max: 8